import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function getPath(target, keyPath) {
  return keyPath.split(".").reduce((acc, key) => (acc ? acc[key] : undefined), target);
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../tokens");

test("card runtime component tokens exist", () => {
  const cardCover = readJson(path.join(root, "comp/card-cover-frame.json"));
  const composite = readJson(path.join(root, "comp/composite-card-window.json"));
  const button = readJson(path.join(root, "comp/button.json"));
  const input = readJson(path.join(root, "comp/input.json"));
  const checkbox = readJson(path.join(root, "comp/checkbox.json"));
  const radio = readJson(path.join(root, "comp/radio.json"));
  const sw = readJson(path.join(root, "comp/switch.json"));
  const select = readJson(path.join(root, "comp/select.json"));
  const dialog = readJson(path.join(root, "comp/dialog.json"));
  const popover = readJson(path.join(root, "comp/popover.json"));
  const tabs = readJson(path.join(root, "comp/tabs.json"));
  const menu = readJson(path.join(root, "comp/menu.json"));
  const tooltip = readJson(path.join(root, "comp/tooltip.json"));
  const form = readJson(path.join(root, "comp/form.json"));
  const virtualList = readJson(path.join(root, "comp/virtual-list.json"));
  const dataGrid = readJson(path.join(root, "comp/data-grid.json"));
  const tree = readJson(path.join(root, "comp/tree.json"));
  const dateTime = readJson(path.join(root, "comp/date-time.json"));
  const commandPalette = readJson(path.join(root, "comp/command-palette.json"));
  const navigationSplitView = readJson(path.join(root, "comp/navigation-split-view.json"));
  const splitPane = readJson(path.join(root, "comp/split-pane.json"));
  const dockPanel = readJson(path.join(root, "comp/dock-panel.json"));
  const inspector = readJson(path.join(root, "comp/inspector.json"));
  const panelHeader = readJson(path.join(root, "comp/panel-header.json"));
  const cardShell = readJson(path.join(root, "comp/card-shell.json"));
  const toolWindow = readJson(path.join(root, "comp/tool-window.json"));
  const errorBoundary = readJson(path.join(root, "comp/error-boundary.json"));
  const loadingBoundary = readJson(path.join(root, "comp/loading-boundary.json"));
  const notification = readJson(path.join(root, "comp/notification.json"));
  const toast = readJson(path.join(root, "comp/toast.json"));
  const emptyState = readJson(path.join(root, "comp/empty-state.json"));
  const skeleton = readJson(path.join(root, "comp/skeleton.json"));
  const view = readJson(path.join(root, "comp/view.json"));
  const box = readJson(path.join(root, "comp/box.json"));
  const stack = readJson(path.join(root, "comp/stack.json"));
  const inline = readJson(path.join(root, "comp/inline.json"));
  const grid = readJson(path.join(root, "comp/grid.json"));
  const section = readJson(path.join(root, "comp/section.json"));
  const scrollView = readJson(path.join(root, "comp/scroll-view.json"));
  const spacer = readJson(path.join(root, "comp/spacer.json"));
  const divider = readJson(path.join(root, "comp/divider.json"));
  const splitView = readJson(path.join(root, "comp/split-view.json"));
  const text = readJson(path.join(root, "comp/text.json"));
  const label = readJson(path.join(root, "comp/label.json"));
  const icon = readJson(path.join(root, "comp/icon.json"));
  const iconButton = readJson(path.join(root, "comp/icon-button.json"));
  const toggleButton = readJson(path.join(root, "comp/toggle-button.json"));
  const badge = readJson(path.join(root, "comp/badge.json"));
  const tag = readJson(path.join(root, "comp/tag.json"));
  const avatar = readJson(path.join(root, "comp/avatar.json"));
  const spinner = readJson(path.join(root, "comp/spinner.json"));
  const progress = readJson(path.join(root, "comp/progress.json"));
  const textField = readJson(path.join(root, "comp/text-field.json"));
  const textArea = readJson(path.join(root, "comp/text-area.json"));
  const searchField = readJson(path.join(root, "comp/search-field.json"));
  const secureField = readJson(path.join(root, "comp/secure-field.json"));
  const segmentedControl = readJson(path.join(root, "comp/segmented-control.json"));
  const comboBox = readJson(path.join(root, "comp/combo-box.json"));
  const numberInput = readJson(path.join(root, "comp/number-input.json"));
  const stepper = readJson(path.join(root, "comp/stepper.json"));
  const slider = readJson(path.join(root, "comp/slider.json"));
  const datePicker = readJson(path.join(root, "comp/date-picker.json"));
  const timePicker = readJson(path.join(root, "comp/time-picker.json"));
  const image = readJson(path.join(root, "comp/image.json"));
  const media = readJson(path.join(root, "comp/media.json"));
  const errorState = readJson(path.join(root, "comp/error-state.json"));

  assert.ok(getPath(cardCover, "chips.comp.card-cover-frame.border.radius"));
  assert.ok(getPath(cardCover, "chips.comp.card-cover-frame.status.color.error"));
  assert.ok(getPath(composite, "chips.comp.composite-card-window.overlay.surface"));
  assert.ok(getPath(composite, "chips.comp.composite-card-window.status.color.error"));
  assert.ok(getPath(button, "chips.comp.button.root.surface.idle"));
  assert.ok(getPath(input, "chips.comp.input.root.border.error"));
  assert.ok(getPath(checkbox, "chips.comp.checkbox.control.surface.checked"));
  assert.ok(getPath(radio, "chips.comp.radio.control.surface.checked"));
  assert.ok(getPath(sw, "chips.comp.switch.track.surface.on"));
  assert.ok(getPath(select, "chips.comp.select.content.surface"));
  assert.ok(getPath(select, "chips.comp.select.option.surface.highlighted"));
  assert.ok(getPath(select, "chips.comp.select.option.text.color"));
  assert.ok(getPath(dialog, "chips.comp.dialog.content.surface"));
  assert.ok(getPath(dialog, "chips.comp.dialog.header.color"));
  assert.ok(getPath(dialog, "chips.comp.dialog.actions.gap"));
  assert.ok(getPath(popover, "chips.comp.popover.content.border"));
  assert.ok(getPath(tabs, "chips.comp.tabs.trigger.surface.active"));
  assert.ok(getPath(menu, "chips.comp.menu.group.label.color"));
  assert.ok(getPath(menu, "chips.comp.menu.item.surface.active"));
  assert.ok(getPath(menu, "chips.comp.menu.separator.thickness"));
  assert.ok(getPath(tooltip, "chips.comp.tooltip.content.text.color"));
  assert.ok(getPath(form, "chips.comp.form.control.border.error"));
  assert.ok(getPath(form, "chips.comp.form.hint.color"));
  assert.ok(getPath(virtualList, "chips.comp.virtual-list.item.surface.active"));
  assert.ok(getPath(dataGrid, "chips.comp.data-grid.toolbar.surface"));
  assert.ok(getPath(dataGrid, "chips.comp.data-grid.header.sort.color"));
  assert.ok(getPath(dataGrid, "chips.comp.data-grid.row.surface.hover"));
  assert.ok(getPath(dataGrid, "chips.comp.data-grid.pagination.gap"));
  assert.ok(getPath(dataGrid, "chips.comp.data-grid.row.surface.selected"));
  assert.ok(getPath(tree, "chips.comp.tree.item.surface.selected"));
  assert.ok(getPath(tree, "chips.comp.tree.disclosure.color"));
  assert.ok(getPath(tree, "chips.comp.tree.group.guide.color"));
  assert.ok(getPath(dateTime, "chips.comp.date-time.input.border.error"));
  assert.ok(getPath(commandPalette, "chips.comp.command-palette.input.surface.idle"));
  assert.ok(getPath(commandPalette, "chips.comp.command-palette.item.surface.active"));
  assert.ok(getPath(commandPalette, "chips.comp.command-palette.group.label.color"));
  assert.ok(getPath(navigationSplitView, "chips.comp.navigation-split-view.sidebar.surface"));
  assert.ok(getPath(navigationSplitView, "chips.comp.navigation-split-view.detail.surface"));
  assert.ok(getPath(navigationSplitView, "chips.comp.navigation-split-view.divider.color"));
  assert.ok(getPath(splitPane, "chips.comp.split-pane.handle.surface.active"));
  assert.ok(getPath(dockPanel, "chips.comp.dock-panel.tab.surface.active"));
  assert.ok(getPath(inspector, "chips.comp.inspector.section.header.surface.active"));
  assert.ok(getPath(panelHeader, "chips.comp.panel-header.action.surface.active"));
  assert.ok(getPath(cardShell, "chips.comp.card-shell.border.color"));
  assert.ok(getPath(toolWindow, "chips.comp.tool-window.control.surface.active"));
  assert.ok(getPath(errorBoundary, "chips.comp.error-boundary.root.border.error"));
  assert.ok(getPath(loadingBoundary, "chips.comp.loading-boundary.skeleton.surface.active"));
  assert.ok(getPath(notification, "chips.comp.notification.action.surface.active"));
  assert.ok(getPath(toast, "chips.comp.toast.close.color"));
  assert.ok(getPath(emptyState, "chips.comp.empty-state.description.color"));
  assert.ok(getPath(skeleton, "chips.comp.skeleton.item.surface.active"));
  assert.ok(getPath(view, "chips.comp.view.content.surface"));
  assert.ok(getPath(box, "chips.comp.box.root.radius"));
  assert.ok(getPath(stack, "chips.comp.stack.root.gap"));
  assert.ok(getPath(inline, "chips.comp.inline.root.gap"));
  assert.ok(getPath(grid, "chips.comp.grid.item.surface"));
  assert.ok(getPath(section, "chips.comp.section.divider.color"));
  assert.ok(getPath(scrollView, "chips.comp.scroll-view.scrollbar.thumb"));
  assert.ok(getPath(spacer, "chips.comp.spacer.root.size"));
  assert.ok(getPath(divider, "chips.comp.divider.root.thickness"));
  assert.ok(getPath(splitView, "chips.comp.split-view.detail.surface"));
  assert.ok(getPath(text, "chips.comp.text.root.color.default"));
  assert.ok(getPath(label, "chips.comp.label.required-indicator.color"));
  assert.ok(getPath(icon, "chips.comp.icon.root.opsz"));
  assert.ok(getPath(iconButton, "chips.comp.icon-button.root.size"));
  assert.ok(getPath(toggleButton, "chips.comp.toggle-button.root.surface.pressed"));
  assert.ok(getPath(badge, "chips.comp.badge.root.surface.warning"));
  assert.ok(getPath(tag, "chips.comp.tag.close.color.hover"));
  assert.ok(getPath(avatar, "chips.comp.avatar.fallback.color"));
  assert.ok(getPath(spinner, "chips.comp.spinner.motion.duration"));
  assert.ok(getPath(progress, "chips.comp.progress.range.surface.indeterminate"));
  assert.ok(getPath(textField, "chips.comp.text-field.root.border.error"));
  assert.ok(getPath(textArea, "chips.comp.text-area.control.color"));
  assert.ok(getPath(searchField, "chips.comp.search-field.clear.color.hover"));
  assert.ok(getPath(secureField, "chips.comp.secure-field.toggle.color.idle"));
  assert.ok(getPath(segmentedControl, "chips.comp.segmented-control.item.surface.selected"));
  assert.ok(getPath(comboBox, "chips.comp.combo-box.option.surface.highlighted"));
  assert.ok(getPath(numberInput, "chips.comp.number-input.root.border.error"));
  assert.ok(getPath(stepper, "chips.comp.stepper.increment.surface.active"));
  assert.ok(getPath(slider, "chips.comp.slider.thumb.surface.active"));
  assert.ok(getPath(datePicker, "chips.comp.date-picker.cell.surface.selected"));
  assert.ok(getPath(timePicker, "chips.comp.time-picker.option.surface.selected"));
  assert.ok(getPath(image, "chips.comp.image.fallback.surface"));
  assert.ok(getPath(media, "chips.comp.media.control.surface.active"));
  assert.ok(getPath(errorState, "chips.comp.error-state.root.border.error"));
});

test("system token layer exists", () => {
  const sys = readJson(path.join(root, "sys.json"));

  assert.ok(getPath(sys, "chips.sys.color.surface"));
  assert.ok(getPath(sys, "chips.sys.color.error"));
  assert.equal(getPath(sys, "chips.sys.icon.color"), "{chips.ref.color.gray-1000}");
  assert.equal(getPath(sys, "chips.sys.icon.size"), "1em");
  assert.equal(getPath(sys, "chips.sys.icon.fill"), 0);
  assert.equal(getPath(sys, "chips.sys.icon.wght"), 400);
  assert.equal(getPath(sys, "chips.sys.icon.grad"), 0);
  assert.equal(getPath(sys, "chips.sys.icon.opsz"), 24);
});

test("layout token layer covers primitive layout constants", () => {
  const layout = readJson(path.join(root, "layout.json"));

  assert.equal(getPath(layout, "chips.layout.density.compact"), "32cpx");
  assert.equal(getPath(layout, "chips.layout.density.comfortable"), "40cpx");
  assert.equal(getPath(layout, "chips.layout.density.spacious"), "48cpx");
  assert.equal(getPath(layout, "chips.layout.gap.sm"), "8cpx");
  assert.equal(getPath(layout, "chips.layout.gap.md"), "12cpx");
  assert.equal(getPath(layout, "chips.layout.size.grid-min-item"), "160cpx");
  assert.equal(getPath(layout, "chips.layout.size.split-primary-min"), "180cpx");
  assert.equal(getPath(layout, "chips.layout.size.split-secondary-min"), "220cpx");
  assert.equal(getPath(layout, "chips.layout.size.navigation-primary-min"), "160cpx");
  assert.equal(getPath(layout, "chips.layout.divider.thickness"), "1px");
  assert.equal(getPath(layout, "chips.layout.focus.outline-width"), "1px");
  assert.equal(getPath(layout, "chips.layout.focus.outline-offset"), "2px");
  assert.equal(getPath(layout, "chips.layout.breakpoint.regular"), "768cpx");
  assert.equal(getPath(layout, "chips.layout.safe-area.block-start"), "env(safe-area-inset-top, 0px)");
});
