export const ErrorCode = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_EXISTS: 'AUTH_USER_EXISTS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSION: 'AUTH_INSUFFICIENT_PERMISSION',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ACCOUNT_DISABLED: 'USER_ACCOUNT_DISABLED',

  // Room
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FORBIDDEN: 'ROOM_FORBIDDEN',

  // Card
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_FORBIDDEN: 'CARD_FORBIDDEN',
  CARD_PIPELINE_ERROR: 'CARD_PIPELINE_ERROR',

  // Box
  BOX_NOT_FOUND: 'BOX_NOT_FOUND',
  BOX_FORBIDDEN: 'BOX_FORBIDDEN',

  // Upload
  FILE_TYPE_INVALID: 'FILE_TYPE_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_CORRUPT: 'FILE_CORRUPT',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // General
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
